### ISSUE TITLE
add support to check both VSCode and VSCodeium

### ISSUE THREAD

**Issue by dev-abderrahim** [MrMarble/vscode-search-provider#2]
yeah I think it possible to do that just add VSCodium storage file path to check dir `~/.config/VSCodium/User/globalStorage/storage.json`.  I have no experience with nodejs, I just edited the already declared path in `provider.js` :)

**Comment by MrMarble** [comment]
Sure! I only use vscode, so that was the main focus, I'll try later with vscodium and other versions (like insiders) and change whatever is needes

**Comment by MrMarble** [comment]
Once the version in published on gnome-extensions website I'll merge it to main
