### ISSUE TITLE
Add option to hide dev containers

### ISSUE THREAD

**Issue by ai** [MrMarble/vscode-search-provider#4]
I use [dev container](https://code.visualstudio.com/docs/devcontainers/containers) to isolate project from the system.

But every Docker container build for the project creates an item in the search results.

Can we hide them (or add option to hide)?

![Captura desde 2024-06-01 17-00-06](https://github.com/MrMarble/vscode-search-provider/assets/19343/32632c00-4a79-4344-b033-0ba6354dda58)

**Comment by MrMarble** [comment]
Hi! I'll look into it, seems like a strange way to handle dev containers, saving each build as a workspace...

I have to do some testing to find a good way of solving this, thanks for opening the issue!

**Comment by MrMarble** [comment]
This seems to be as expected, VScode also has multiple version one for each dev container, and they appear as normal workspaces, so I'll filter out the remote containers for now, as opening the default workspace will ask for using the dev container anyway
![image](https://github.com/MrMarble/vscode-search-provider/assets/4268580/c6cc6040-9bda-4ff5-a2ec-8bf3de7eb24c)
![image](https://github.com/MrMarble/vscode-search-provider/assets/4268580/3251ea6d-ac59-481b-b8c4-a60b09dd24f9)

**Comment by MrMarble** [comment]
Latest version with changes is in review by extensions.gnome.org, you can update manually or wait a bit for the automatic update

**Comment by ai** [comment]
It was quick. Thanks a lot. Works as a charm.

I sent a small donation since we are community to help each other, and not a free support ❤️

**Comment by MrMarble** [comment]
> It was quick. Thanks a lot. Works as a charm.
> 
> I sent a small donation since we are community to help each other, and not a free support ❤️

Thank you!!
