### ISSUE TITLE
Need `decodeURIComponent(path)` to unescape url

### ISSUE THREAD

**Issue by d-enk** [MrMarble/vscode-search-provider#8]

**Comment by MrMarble** [comment]
Fixed in https://github.com/MrMarble/vscode-search-provider/releases/tag/v2.0.0

**Comment by d-enk** [comment]
@MrMarble also needed for the name

![image_2024-06-10_11-24-39](https://github.com/MrMarble/vscode-search-provider/assets/43112758/68e3fdfb-2d5d-49ab-bb5e-37aeffe4691a)

**Comment by d-enk** [comment]
just

```js
for (const path of paths.map(decodeURIComponent)) {
```

https://github.com/MrMarble/vscode-search-provider/blob/ec9e3f67e128f1fd1a40665696bc41e744013dc2/src/provider.ts#L40

**Comment by MrMarble** [comment]
How is that the name? 
I only pick the last part of the path as the name `const name = path.split("/").pop()!;`, how do you get `gnome-shell/extensions/vscode-search-provider@mrmarble.github.com` as the workspace name? should be only `vscode-search-provider@mrmarble.github.com` in that case

**Comment by d-enk** [comment]
my hack, it’s more convenient for me

just, my folder hierarchy like

`.../github.com/MrMarble/vscode-search-provider`
`.../my.git/group/repo/`


sorry if I misled you

**Comment by MrMarble** [comment]
Pushed the changes to main and submitted it for review as well
